[phases.setup]
aptPkgs = ["python3-dev", "build-essential"]

[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt && chmod +x start.sh"

[deploy]
startCommand = "./start.sh"